environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - "SET PATH=%C:\\Python37-x64%;%C:\\Python37-x64%\\Scripts;%PATH%"
  - "python -m pip install pip wheel setuptools pytest -U"
  - "python setup.py develop"

build: off
